#!/bin/bash
 sudo hostnamectl set-hostname web  
 sudo yum install httpd -y 
 sudo systemctl start httpd
 sudo systemctl enable httpd 
 sudo echo "<h1> Welcome To LandmarkTech </h1>" >> /var/www/html/index.html
 sudo echo "<h1> DevOps is good </h1> " >> /var/www/html/index.html
 su - ec2-user  
